# -*- coding: utf-8 -*-
"""#106 | Correlation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kuF2IASIQRW8VE3e4vdR4fFh7t1i3kAm
"""

import csv
import numpy

with open('mrrk.csv', newline='') as f:
  reader = csv.reader(f)
  fileData = list(reader)

fileData.pop(0)
sz = []
time = []

for i in range(len(fileData)):
  size = fileData[i][1]
  tim = fileData[i][2]
  sz.append(float(size))
  time.append(float(tim))

coefficient = numpy.corrcoef(sz, time)
print(round(coefficient[0,1], 1))

import csv
import numpy

with open('cup.csv', newline='') as f:
  reader = csv.reader(f)
  fileData = list(reader)

fileData.pop(0)
mrk = []
time = []

for i in range(len(fileData)):
  marks = fileData[i][1]
  tim = fileData[i][2]
  mrk.append(float(marks))
  time.append(float(tim))

coefficient = numpy.corrcoef(mrk, time)
print(round(coefficient[0,1], 1))